### ISSUE TITLE
Add support for SCTs over TLS extension and OCSP stapling

### ISSUE THREAD

**Issue by mattmook** [babylonhealth/certificate-transparency-android#2]
Research into [server-side adoption of certificate transparency](https://github.com/Babylonpartners/certificate-transparency-android/files/2542907/pam18.pdf) shows that X.509v3 extensions are currently the most popular way to retrieve SCTs, however to adhere to the [Certificate Transparency v2 spec](https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-29#section-8.1.1) the library needs to add support for retrieving these over TLS extensions and OCSP stapling.

The same research shows how this can be [implemented in pure Java](https://github.com/Babylonpartners/certificate-transparency-android/files/2542922/pam18-code.zip) with no native libraries.

> See [Server-side Adoption of Certificate Transparency](https://www.ida.liu.se/~nikca89/papers/pam18.html)

**Comment by RJPercival** [comment]
This is also required to adhere to the current Certificate Transparency spec. [RFC6962, section 3.3](https://tools.ietf.org/html/rfc6962#section-3.3), says "TLS clients MUST implement all three mechanisms." There is substantial use of the TLS extension (for example, Google domains typically serve SCTs via TLS extension rather than x.509v3 extension).

**Comment by mattmook** [comment]
As part of this work `DefaultPolicy` will need to be updated to accommodate this.

If the SCTs were provided by TLS extensions or OCSP stapling then we only require two valid entries (Chrome forces 2 because of diversity rules), otherwise embedded SCTs continue to be checked as they are currently.

[Certificate Transparency in Chrome](https://github.com/chromium/ct-policy/blob/master/ct_policy.md#qualifying-certificate)
[Apple's Certificate Transparency policy](https://support.apple.com/en-gb/HT205280)
See Chromium source [CheckCTPolicyCompliance](https://chromium.googlesource.com/chromium/src/+/lkgr/components/certificate_transparency/chrome_ct_policy_enforcer.cc)

**Comment by mattmook** [comment]
Closing as moved issue to https://github.com/appmattus/certificatetransparency/issues/11
