### ISSUE TITLE
Android: Support for charles proxy for debugging

### ISSUE THREAD

**Issue by preethasuraj** [babylonhealth/certificate-transparency-android#26]
Does the CT work if connected to charles proxy. We use this for debugging and tracking the api calls. When I am connected to Chales, I see that CT is failing with the logs 
 at com.babylon.certificatetransparency.chaincleaner.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:81)
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyBase.verifyCertificateTransparency(CertificateTransparencyBase.kt:71)
        at com.babylon.certificatetransparency.internal.verifier.CertificateTransparencyInterceptor.intercept(CertificateTransparencyInterceptor.kt:44)

Is this the expected behavior? Is there a way to get around it, so that we can have the CT enabled even when connected to charles.

**Comment by mattmook** [comment]
This would be expected behaviour as CT is there to stop man-in-the-middle attacks such as using Charles proxy. The certificate Charles uses won't have [SCT](http://www.certificate-transparency.org/faq#TOC-What-is-an-SCT-) entries, and nor should it due to the type of certificate Charles uses.

However, what you could do, assuming you're using Android, would be to allow failures in debug mode, something like this:

```
val interceptor = certificateTransparencyInterceptor {
    +"my.example.com"

   failOnError = BuildConfig.DEBUG
}
```

**Comment by preethasuraj** [comment]
Thank you for the suggestion.
I tried the failOnError = BuildConfig.DEBUG option, and I am having a debug build with this value true but still I am getting 

failed to get ..... )java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Also as by default failOnError is true, how does it work

**Comment by mattmook** [comment]
The exception above makes it look as though you don't have the Charles root cert installed on your test device. To do that you usually need to visit http://www.charlesproxy.com/getssl/ on that device to download it and install it.

Dependent on the version of Android you are using you will likely need to also allow your app accept user installed certs by configuring the `network_security_config.xml` as follows:

```
<network-security-config>  
      <debug-overrides>  
           <trust-anchors>  
                <!-- Trust user added CAs while debuggable only -->
                <certificates src="user" />  
           </trust-anchors>  
      </domain-config>  
 </network-security-config>
```

This blog post has some more details about that https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html

**Comment by preethasuraj** [comment]
Thank you. That worked

**Comment by shivsahni** [comment]
Hey @mattmook,

First of all kudos for the amazing work that you have done!

While intercepting traffic using a proxy server(Charles, Burp Suite, etc.) we install the cert manually to the device trust store. If the certificate is added [properly](https://blog.nviso.eu/2017/12/22/intercepting-https-traffic-from-apps-on-android-7-using-magisk-burp/)(overriding the default NSC configuration) we should be able to intercept the traffic in spite of CT checks in place based on the Mozilla docs there would be no enforcement. Can you please look into this?


`Root CAs manually added to the trust store override and suppress Expect-CT reports/enforcement.`
`Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT`
