### ISSUE TITLE
Build Failed DexArchiveBuilderException , Illegal class file: Class module-info is missing a super type

### ISSUE THREAD

**Issue by kaustav07** [babylonhealth/certificate-transparency-android#27]
After including the library I am unable to run the app, build is failing, I haven't used the library in code yet. Below is a screenshot - 

![Screenshot 2019-08-20 at 2 24 58 PM](https://user-images.githubusercontent.com/11479382/63334347-de8f9180-c358-11e9-8239-7fe444a22ecb.png)

**Comment by mattmook** [comment]
Looking at the logs above this looks like its related to Firebase performance plugin - see https://issuetracker.google.com/issues/131114388

Supposedly fixed with Android Gradle 3.5.0-beta05

**Comment by mattmook** [comment]
If this is still an issue let me know.
