### ISSUE TITLE
Does this library protect against MITM over gstatic.com domain?

### ISSUE THREAD

**Issue by dlecan** [babylonhealth/certificate-transparency-android#32]
Hello,

Thank you for this project, you have done a great job by implementing certificate transparency for Android. My domain can be served securely on Android applications.

If I understand correctly the code, everything relies on the `gstatic.com` domain and its security: how is domain trusted? How is it protected against MITM?

Thank you

**Comment by mattmook** [comment]
This is protected by verifying the content using a public key, stored in [GooglePublicKey.kt](https://github.com/babylonhealth/certificate-transparency-android/blob/master/lib/src/main/kotlin/com/babylon/certificatetransparency/internal/loglist/GooglePublicKey.kt) and verified by [LogListVerifier.kt](https://github.com/babylonhealth/certificate-transparency-android/blob/master/lib/src/main/kotlin/com/babylon/certificatetransparency/internal/loglist/parser/LogListVerifier.kt), that the files served from gstatic.com are signed with.

With that in mind as long as Google's private key is well protected then the content can be trusted. Of course it is impossible to get away from all potential security vulnerabilities and indeed a possible attack that is still currently possible is for someone to present old content that was previously signed with the valid key, i.e. a replay attack. We are in the process of looking into how we could address this.

**Comment by dlecan** [comment]
Ok, I missed this file.
So, instead of pinning our own certificate fingerprint, we're now pinning Google's public key :sweat_smile: 

Any chance to be able to read an alternate CT log? Would it improve security?

**Comment by mattmook** [comment]
This file contains a list of log servers and their public keys along with their validity, so for example if a particular log server were shown to be bad then its status in the file will change.

These public keys are what is then used to verify the SCT entries from the server certificate and you are ensuring there are at least 2 valid entries (more if the certificate lifespan is longer) - these entries are typically from different log server providers (i.e. run by different companies)

Reading the log list from an alternative source I'm not sure makes a huge amount of difference, ultimately you still need to trust that source, of course you could manage this file yourself but would ultimately still have to read this data from somewhere and would still want an additional protection on it than just https.

Alternative sources do exist, such as from Apple, see https://support.apple.com/en-gb/HT205280, however Apple do not provide a signature, that I know of, so you have no way of verifying the legitimacy of the content when you read it.

It is also possible to embed this data as part of the app, however, I'm not sure what length of validity is sensible to use, and your app will become dependent on the constant updating of this data being pushed out in app updates. Unfortunately my own question about how Chrome manages this data remains unanswered - https://groups.google.com/forum/#!topic/certificate-transparency/N4EiXU1VI-M.
