### ISSUE TITLE
[Question] I want to contribute, how do I build the project?

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [babylonhealth/certificate-transparency-android#36]
We found this library awesome and we wanted to contribute, but before that, we want to test our changes in our project.

We tried building the project just like you do on circle ci, using `./gradlew build`.

It generated the `aar` for the `android` module, but the `lib` module didn't come as transitive dependency, making its files not accessible when consuming the generated `aar`.

Can you help us build the project? Also, it would be cool having this in the `CONTRIBUTING.MD`

**Comment by mattmook** [comment]
Certainly the easiest way to consume the library is through the gradle dependencies... i.e.

```groovy
// Android (will automatically include the below dependency)
implementation 'com.babylon.certificatetransparency:certificatetransparency-android:<latest-version>'

// Java
implementation 'com.babylon.certificatetransparency:certificatetransparency:<latest-version>'
```

That being said, if you are already using the project and want to test the impact of your changes without the need to deploy artifacts, the easiest way is to use gradles composite builds, see https://docs.gradle.org/current/userguide/composite_builds.html.

You should be able to add (not tested) the following to your projects settings.gradle which will automatically substitute in this library in a way that makes it easy to edit and test.

```kotlin
includeBuild("path-to-root-of-certificate-transparency-android")
```
