### ISSUE TITLE
Can we include CT for all urls by specifying *.*

### ISSUE THREAD

**Issue by preethasuraj** [babylonhealth/certificate-transparency-android#37]
Why we have to give each domain as +*.domain.com.
Is there any restriction for enabling for all domains by default and restricting whichever does not have CT by adding -*.domain.com

**Comment by mattmook** [comment]
I've added support for this which will go out in the next release. To use, you'll have to configure as follows:

```kotlin
        certificateTransparencyInterceptor {
            +"*.*"
            -"exclude.example.com
        }
```
