### ISSUE TITLE
seconds/milliseconds variation when determining if a SCT is from a retired log

### ISSUE THREAD

**Issue by kSriramji** [babylonhealth/certificate-transparency-android#40]
Version -1.4
Error - Failure: Too few trusted SCTs, required 2, found 1 in {u9nfvB+KcbWTlCOXqpJ7RzhXlQqrUugakJZkNo4e0YU==Valid SCT, h3W/51l8+IxDmV+9827/Vo1HVjb/SrVgwbTq/16ggw8==SCT timestamp, 1573258714144, is greater than the log server validity, 1588550440.}

**Comment by AlCutter** [comment]
A bit more context in [this thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/certificate-transparency/_mPMjt1lxJ8/6pZYuhE6AgAJ) over on the certificate-transparency list.

**Comment by mattmook** [comment]
Thanks for the report.

The documentation around the v1 schema was particularly vague so I can see how this bug crept in. We are no longer supporting the v1 schema and as such we will not be fixing this bug against an older version of the library.

Please upgrade to at least v0.2.0 which implements v2 schema support.
