### ISSUE TITLE
Revoked certification checking in android

### ISSUE THREAD

**Issue by pranay-raut26** [babylonhealth/certificate-transparency-android#51]
I have performed the CT in the application and it is working as expected, But now I am facing problems with the certificate revocation checking. Is there any way I can perform revocation checking in Android?

**Comment by yschimke** [comment]
I've got a branch of certifikit (a square project) that adapts netty OCSP support.  Would it be worth porting this to an interceptor here?

https://github.com/cashapp/certifikit/pull/56/files

**Comment by ben-j69** [comment]
@mattmook sorry to ask this question but what is the security provided by this library if it authorizes access to domains with revoked certificates ? Maybe there is something I don't understand...
Thanks

**Comment by mattmook** [comment]
Hi @ben-j69 it's not the purpose of this library to protect from revoked certificates. This is an incredibly hard to solve problem and it is worth reading https://scotthelme.co.uk/revocation-is-broken/ for more background. Needless to say I would argue that revocation is flawed along with the broken implementations in mobile and web browsers.

Certificate transparency tries to approach the problem by reducing the chance of a rogue certificate being generated in the first place as it has to be publicly logged and is therefore detectable. In essence CT checks are verifying that the certificate has been publicly logged.

**Comment by mattmook** [comment]
Hi @yschimke ideally any revocation code should really be broken out into a separate library so this library keeps a clear purpose.

The OCSP checking code looks cool and it would be great to adapt it into an interceptor.

**Comment by yschimke** [comment]
@mattmook no problem.  No plan from my side.

Also for what it's worth, I don't see a need to solve this myself if Android and Browser engineers have mostly agreed it's too hard.  But in the context of a tool to check status and correctness of certificates it was useful.

I found the JVM in built checking to be awkwardly implemented with 3 system properties and really not focused around the real world usecases I would have.

**Comment by mattmook** [comment]
In terms of the CT library there is nothing more to do with revocation now I've added some documentation to what the project currently offers.

Given the time revocation needs an implementation in an independent library.
