### ISSUE TITLE
Traffic Interception In Certificate Transparency

### ISSUE THREAD

**Issue by shivsahni** [babylonhealth/certificate-transparency-android#55]
Hey @mattmook,

First of all kudos for the amazing work that you and the team have done!

While intercepting traffic using a proxy server(Charles, Burp Suite, etc.) we install the cert manually to the device trust store. If the certificate is added properly(overriding the default NSC configuration) we should be able to intercept the traffic in spite of CT checks in place based on the Mozilla docs there would be no enforcement. Can you please look into this?

Root CAs manually added to the trust store override and suppress Expect-CT reports/enforcement.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT

However, you mentioned that the `certificate-transparency-android` would be blocking the requests:

> If when you run your app, certificate transparency causes a refused connection then you are all set. In this scenario, you also shouldn’t see your requests in the mitmproxy console window
Ref: https://medium.com/babylon-engineering/android-security-certificate-transparency-601c18157c44

Does this mean that you are explicitly blocking the requests in the case the CT checks fail which would be the case when we would be using the proxy server for traffic interception as the cert that the proxy would present would have the CNAME but won't have the SCTs for it?

**Comment by shivsahni** [comment]
Hey @mattmook,

Thanks for your reply. Since we do not have any specific API that could let us know about the user certificates in the device's trust store we are rejecting the connection requests even if the cert is locally installed unlike other CT clients(Chromium)

**Comment by matheuslc** [comment]
@shivsahni Rejecting connections event if the cert is locally installed makes Charles unable to inspect any HTTP connection? So, even if the cert was installed on the machine, CT will block it. This is true?
