### ISSUE TITLE
Does the lib support IP address ?

### ISSUE THREAD

**Issue by ChunyuanCai** [babylonhealth/certificate-transparency-android#61]
I use OKHttp in my project and wonder whether I could use ip instead domain (wildcards) as below ?

```
val interceptor = certificateTransparencyInterceptor {
    +"my_ip1",
    +"my_ip2"
}

val client = OkHttpClient.Builder().apply {
    addNetworkInterceptor(interceptor)
}.build()
```

**Comment by mattmook** [comment]
In theory there's no reason why we couldn't add support, it's just not a scenario we'd thought much about.

Just so I can better understand the use case, is there a particular reason why you'd prefer to use IP address?
