### ISSUE TITLE
SerializationException while getting ParsedLogEntry using HttpLogClient for CTlog url -> http://ct.googleapis.com/logs/argon2021/ct/v1/

### ISSUE THREAD

**Issue by prasadkatre** [babylonhealth/certificate-transparency-android#68]
Hi, 
I am trying to retrieve the certificate log entries from Ctlog servers using HttpLogClient  from com.babylon.certificatetransparency:certificatetransparency:0.3.0 jar but I am getting Serialization exception as mentioned below while getting the parseLogEntry.

Exception in thread "main" com.babylon.certificatetransparency.internal.exceptions.SerializationException: Extra data corrupted.
	at com.babylon.certificatetransparency.internal.serialization.Deserializer.parsePreCertificateChainEntry(Deserializer.kt:266)
	at com.babylon.certificatetransparency.internal.serialization.Deserializer.parseLogEntry(Deserializer.kt:153)
	at com.babylon.certificatetransparency.internal.logclient.model.network.GetEntriesResponse.toParsedLogEntries(GetEntriesResponse.kt:68)
	at com.babylon.certificatetransparency.internal.logclient.HttpLogClient.getLogEntries(HttpLogClient.kt:116)
	at com.qualys.certificate.transparency.TestCtLog.main(TestCtLog.java:24)

------------------------------------------------------------------------------------------
public class TestCtLog {
	public static void main(String args[]) {

		try {
			HttpLogClient client = (HttpLogClient) LogClientFactory.INSTANCE
					.create("http://ct.googleapis.com/logs/argon2021/ct/v1/");
			// SignedTreeHead sth = client.getLogSTH();
			SignedTreeHead sth = client.getLogSth$certificatetransparency();
			List<com.babylon.certificatetransparency.internal.logclient.model.ParsedLogEntry> ent = client
					.getLogEntries(0, 10);

			com.babylon.certificatetransparency.internal.logclient.model.ParsedLogEntry logEntry = ent.get(0);
			LogEntry.X509ChainEntry entry = (X509ChainEntry) logEntry.getLogEntry();
			byte[] leafCert = entry.getLeafCertificate();

			X509Certificate cert = (X509Certificate) CertificateFactory.getInstance("X509")
					.generateCertificate(new ByteArrayInputStream(leafCert));

			System.out.println(cert);
		} catch (CertificateException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}

**Comment by mattmook** [comment]
Hi @prasadkatre I must admit the code was left in there from when I ported it from Google's original library and I've not actually tested this particular functionality.

I imagine that the format now being used has been updated so the code would need to be fixed to support it. If you are able to take a look and create a PR to fix any issues you find that would be much appreciated as I don't have much time in the foreseeable future.

**Comment by mattmook** [comment]
While the log client functionality was something I had always wanted to support, the reality is I don't have the time.

As such going forward I have taken the decision to remove it from the project.

Of course I am happy for anyone else to take on and maintain the code for the log client in an independent library.
