### ISSUE TITLE
Using includeHost() could be error prone

### ISSUE THREAD

**Issue by saran2020** [babylonhealth/certificate-transparency-android#70]
When setting up this library, it's mandatory to set at-least one host to set CT for. Now lets say we have wrongly configured host name (Could be wrong regex or a typo) in `includeHost()` will cause the [enabledForCertificateTransparency(String)](https://github.com/babylonhealth/certificate-transparency-android/blob/b0c7925127b256d83697de4c867739ccc3a8aef3/certificatetransparency/src/main/kotlin/com/babylon/certificatetransparency/internal/verifier/CertificateTransparencyBase.kt#L128) to fail and thus [return a success](https://github.com/babylonhealth/certificate-transparency-android/blob/b0c7925127b256d83697de4c867739ccc3a8aef3/certificatetransparency/src/main/kotlin/com/babylon/certificatetransparency/internal/verifier/CertificateTransparencyBase.kt#L74) (`VerificationResult.Success.DisabledForHost`)

Eg:
```kotlin
.hostnameVerifier(certificateTransparencyHostnameVerifier(
    OkHostnameVerifier.INSTANCE
) {
     +"github.con" // wrong hostname, by mistaked added .co**n** instead of .co**m**
})
```
Will cause all the calls to `github.com` to succeed.

#### Suggestion to resolve
- Make the default as CT enabled for all the hosts

This way people with basic usecase do not need to do additional configuration and this mitigating the issue.

**Comment by mattmook** [comment]
Closed as moved to https://github.com/appmattus/certificatetransparency/issues/17
