### ISSUE TITLE
Use LogClientService in external Java Project?

### ISSUE THREAD

**Issue by Peter0x48** [babylonhealth/certificate-transparency-android#73]
Hi,

I want to use the LogClientService to retrieve CT entries. Is that possible from outside of the project within a Java project?
I found no way so far.

Thanks!

**Comment by mattmook** [comment]
Hi @Peter0x48,

You are right you cannot access `LogClientService` directly.

Instead you should access it through `LogClientFactory`, however, I marked it with Kotlin's `internal` modifier where it should be `public`.

Effectively this means from Java code you should be able to access this:

```java
//noinspection KotlinInternalInJava
LogClient client = LogClientFactory.INSTANCE.create(baseUrl);
```

**Comment by mattmook** [comment]
The next release of the library will have this code public in its own module. As such I'm closing this issue for now.
