### ISSUE TITLE
Migrating away from JCenter

### ISSUE THREAD

**Issue by hustoj2** [babylonhealth/certificate-transparency-android#77]
Hi, first thank you for this library.

We recently learned that starting from May 1, 2021 [JCenter will stop working](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Do you publish only to JCenter currently? We were unable to get this dependency from google() or mavenCentral().

Do you plan to publish all (including older) artifacts in the new place? We're currently on v0.3.0.

**Comment by maxkohne** [comment]
@mattmook any updates on the progress of this?

**Comment by mattmook** [comment]
I will be looking at it this week.

Regarding older artifacts I will see what I can do however it's unlikely these will keep the same groupid and artifact mainly because this project will be moving to a new home shortly too. I'm hoping the old artifacts meet Maven Centrals list of requirements for publishing.

**Comment by mattmook** [comment]
Having taken a quick look at the artifacts from JCenter, we're missing valid artifacts for v0.1.2 and v0.1.3 so those won't be migrated to Maven Central. The rest including v0.3.0 look pretty portable. I've started work to fix the pom files for the artifacts so Maven Central will accept them.

**Comment by mattmook** [comment]
It's worth noting that JCenter will continue to serve packages for 12 months until February 1st 2022. See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by maxkohne** [comment]
> It's worth noting that JCenter will continue to serve packages for 12 months until February 1st 2022. See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

While that is true, you will not be able to submit newer versions of the library after March 31.
