### ISSUE TITLE
Could not resolve com.babylon.certificatetransparency:certificatetransparency-android:0.3.0.

### ISSUE THREAD

**Issue by minichouilleur** [babylonhealth/certificate-transparency-android#81]
Hi,

Since a few days, I encounter this error when gradle syncing my app project :

> Could not resolve com.babylon.certificatetransparency:certificatetransparency-android:0.3.0.
>          > Could not get resource 'https://plugins.gradle.org/m2/com/babylon/certificatetransparency/certificatetransparency-android/0.3.0/certificatetransparency-android-0.3.0.pom'.
>             > Could not GET 'https://plugins.gradle.org/m2/com/babylon/certificatetransparency/certificatetransparency-android/0.3.0/certificatetransparency-android-0.3.0.pom'.
>                > Connect to www-cache-nrs.si.fr.intraorange:3128 [www-cache-nrs.si.fr.intraorange/10.242.190.3] failed: Connection timed out: connect

By following this url , I'm redirected to https://jcenter.bintray.com/com/babylon/certificatetransparency/certificatetransparency-android/0.3.0/certificatetransparency-android-0.3.0.pom with a 403 Forbidden error.

This url works in http and not https.

Do you have any solution to fix that problem ?

Thank you.

**Comment by mattmook** [comment]
I have a mirror of the artifacts on maven central which is hopefully more reliable. These are available at com.appmattus.certificatetransparency:certificatetransparency-android:0.3.0
